server:
  port: 8080
spring:
  application:
    name: shopping-cart-enhancer-svc
    version: V1
  zipkin:
    enabled: true
    base-url: http://zipkin-svc
  sleuth:
    enabled: true
    traceId128: true
    sampler: 
      probability: 1
    async:
      enabled: true
  cloud:
    stream:
      bindings:
        cart-input-channel:
          destination: cart-events
        product-input-channel:
          destination: product-created-event
        cart-details-input-channel:
          destination: cart-details-event  
      kafka:
        streams:
          binder:
            brokers:  http://kafka-svc:9092
            configuration:
              processing.guarantee: exactly_once
              state.dir: shopping-cart-enhancer-svc-6067

        
              